### ISSUE TITLE
how to use the query params in react-native-woocommerce-api?

### ISSUE THREAD

**Issue by najathi** [JamesUgbanu/react-native-woocommerce-api#13]
When I fetch the products, orders, product categories that works fine. But when passing the params, got the error. How to pass the param in react-native-woocommerce-api library?

error is authentication, invalid signature error. How to solve this??

**Comment by najathi** [comment]
### Answer:

I think it should be work

### Open react-native-woocommerce-api.js in node_modules\react-native-woocommerce-api\lib\

then goto line _195 (_getOAuth().authorize function)_ and change:

```
params.qs = this._getOAuth().authorize({
  url: url,
  method: method
});
```
to

```
params.qs = this._getOAuth().authorize({
  url: url + '?' + this.join(data, '&'),
  method: method
});
```

**how to use it ?**

```
wooApi
        .get("products", {per_page: 100})
        .then((products) => {
            console.log("products", products);
        })
        .catch((error) => {
            console.log(error);
        });
```

**Comment by JamesUgbanu** [comment]
Thanks for fixing the issue. Please can you create a pull request for the fix? So i can test and merge to the main branch.
