### ISSUE TITLE
Use WpAPI

### ISSUE THREAD

**Issue by paolosantarsiero** [JamesUgbanu/react-native-woocommerce-api#15]
I try to implement the wc api and it works very well! But i don't understand how can i user wpAPi. For example i want to create a new user...how can i do? Thanks

**Comment by JamesUgbanu** [comment]
Hi @paolosantarsiero, this package is for Woocommerce endpoints alone. However, you can read up on how to use WordPress endpoints here - https://developer.wordpress.org/rest-api/reference/users/#create-a-user and https://wordpress.stackexchange.com/questions/264452/how-do-i-create-a-user-using-the-new-json-api-in-4-7

Do not hesitate to reach out if you have any question.
