### ISSUE TITLE
Issue with params and subscriptions

### ISSUE THREAD

**Issue by alsopgroup** [JamesUgbanu/react-native-woocommerce-api#16]
I am using react-native-woocommerce-api@1.5.0

My API is declared as:

`const WooCommerce = new WooCommerceAPI({
  url: "https://www.abc.com",
  ssl: true,
  consumerKey: "xxxxxxxxxx",
  consumerSecret: "xxxxxxxxxxx",
  wpAPI: true,
  version: "wc/v1",
  queryStringAuth: true,
});`

_Note it is v1 as v3 does not work with subscriptions._

I'm using this code:
`await WooCommerce.get("subscriptions", { status: "active" })
      .then((data) => {
        console.log(data);
      })
      .catch((error) => {
        console.log(error);
      });`

I get this error message in the logs:
`'woocommerce_rest_cannot_view',
  message: 'Sorry, you cannot list resources.',
  data: { status: 401 } }`

It does work without the param:  `await WooCommerce.get("subscriptions",)`

Note subscription params can be found here:  [https://prospress.github.io/subscriptions-rest-api-docs/#list-all-subscriptions](url)

Please advise how I should pass params with subscriptions.  I would also like to pass a specific customer param as well using a variable.

**Comment by JamesUgbanu** [comment]
@alsopgroup try to update to a recent version react-native-woocommerce-api@1.6.0 which has this issue fixed. Thanks

**Comment by alsopgroup** [comment]
Updated today, testing now and will report back.

**Comment by alsopgroup** [comment]
Now when I use:  `    await WooCommerce.get("subscriptions", {
      per_page: 100,
    })`

I get the following error in log:

`{ code: 'rest_invalid_param',
  message: 'Invalid parameter(s): per_page',
  data: 
   { status: 400,
     params: { per_page: 'per_page is not of type integer.' } } }`

**Comment by alsopgroup** [comment]
Also, as per my original syntax, when I try to get active I have the following...

Code:  
`await WooCommerce.get("subscriptions", { status: "active" })`

Log:  
`{ code: 'rest_invalid_param',
  message: 'Invalid parameter(s): status',
  data: 
   { status: 400,
     params: { status: 'status is not one of any, pending, active, on-hold, cancelled, switched, expired, pending-cancel.' } } }`

**Comment by alsopgroup** [comment]
Finally, when I am using a variable for customer....

Code A (variable):
` await WooCommerce.get("subscriptions", { customer: userID })`

Code B (hardcoded):
` await WooCommerce.get("subscriptions", { customer: 310 })`

Log:
`{ code: 'rest_invalid_param',
  message: 'Invalid parameter(s): customer',
  data: 
   { status: 400,
     params: { customer: 'customer is not of type integer.' } } }`

Either params are not being passed correctly or I have a syntax error.  Please advise...

**Comment by alsopgroup** [comment]
Just to try other things, I also tried this with the same result:
`await WooCommerce.get("subscriptions?status=active")`

**Comment by JamesUgbanu** [comment]
I am currently checking through the codes. However, try to query a different endpoint - WooCommerce.get("products", { per_page: 100 }). I want to be sure its not from your code.

I await your response.

**Comment by alsopgroup** [comment]
I am testing as follows:
`await WooCommerce.get("products", { per_page: 100 })
      .then((data) => {
        console.log(data);
      })
      .catch((error) => {
        console.log(error);
      });`

Log:
`{ code: 'rest_invalid_param',
  message: 'Invalid parameter(s): per_page',
  data: 
   { status: 400,
     params: { per_page: 'per_page is not of type integer.' } } }`

**Comment by JamesUgbanu** [comment]
Thanks for the feedback :) I just resolved the issue. Please update to the latest version and try again.

**Comment by alsopgroup** [comment]
Perfecto!  Works as expected now, thanks!

**Comment by shivani2911** [comment]
is there any update abouyt this i'm aslo facing same issue 

{"code": "rest_invalid_param", "data": {"params": {"page": "page is not of type integer."}, "status": 400}, "message": "Invalid parameter(s): page"}
