### ISSUE TITLE
How to get total page count in result?

### ISSUE THREAD

**Issue by Myerden** [JamesUgbanu/react-native-woocommerce-api#18]
Hi, 
I want to get **x-wp-totalpages** and **x-wp-total** header info, is there any way to get these values in response?

**Comment by JamesUgbanu** [comment]
Hi @Myerden,
Can I have look at the response you got?

**Comment by Myerden** [comment]
My code:

```
import WooCommerceAPI from 'react-native-woocommerce-api';

var API = new WooCommerceAPI({
    url: 'https://example.com/',
    ssl: true,
    consumerKey: 'ck_******',
    consumerSecret: 'cs_******',
    wpAPI: true,
    version: 'wc/v3',
    queryStringAuth: true
});

getProducts() {
	API.get('products')
	.then(data => {
	  console.log('data: ' + data);
      this.setState({ products: data });
    })
    .catch(error => {
      console.log(error);
    });
}
```
I got product list as array:

![image](https://user-images.githubusercontent.com/15304742/94377347-77323c80-0129-11eb-94b1-ae88a583490f.png)

![image](https://user-images.githubusercontent.com/15304742/94377361-8adda300-0129-11eb-9dcd-66e4ecc0e6ab.png)

I need to access response headers but the result is only response json.

This is looking related with [this line](https://github.com/JamesUgbanu/react-native-woocommerce-api/blob/86af780be00fd04a827ed82df16d14c449747011/lib/react-native-woocommerce-api.js#L219) of code.

**Comment by JamesUgbanu** [comment]
Hi @Myerden 

Update the latest version and query like this;

```
getProducts() {
	API.get('products', {header: true})
	.then(data => {
	  console.log('data: ' + data);
      this.setState({ products: data });
    })
    .catch(error => {
      console.log(error);
    });
}
```
Please, check it with and without header, lets see if we are getting the correct response.

Thanks

**Comment by Myerden** [comment]
Hi @JamesUgbanu,
Thank you for your support, you saved me.

Here is some working examples; data returns only array of products.

```
getProducts() {
    API.get('products') // or -> API.get('products', {header: false})
	.then(data => {
	  console.log('data: ' + data); // returns array of products 
      this.setState({ products: data });
    })
    .catch(error => {
      console.log(error);
    });
}
```
---
if I set `header: true`, data returns header info and array of products.
Example usage should be like this;

```
getProducts() {
    API.get('products', {header: true})
	.then(data => {
	  console.log('headers: ' + data.header); // returns header info
	  console.log('data: ' + data.data); // returns array of products 
      this.setState({ products: data.data });
    })
    .catch(error => {
      console.log(error);
    });
}
```
or like this

```
getProducts() {
    API.get('products', {header: true})
	.then(({data, header})=> {
	  console.log('headers: ' + header); // returns header info
	  console.log('data: ' + data); // returns array of products 
      this.setState({ products: data });
    })
    .catch(error => {
      console.log(error);
    });
}
```
