### ISSUE TITLE
undefined is not an object (evaluating '_WooAPI.WooAPI.get')

### ISSUE THREAD

**Issue by BennaceurHichem** [JamesUgbanu/react-native-woocommerce-api#20]
I'm working in a local environement and my lcoalhost link is : http://127.0.0.1:81/wordpress/

I added the consumer key and consumer secret, but an error is handled

is it necessary to use a deployed wordpress website ? 

or there is another issue ?

`` 
TypeError: undefined is not an object (evaluating '_WooAPI.WooAPI.get')

This error is located at:
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at `renderApplication.js:39)
``

**Comment by JamesUgbanu** [comment]
Hi there,

Have it deployed first and reopen if the problem persists.

Thanks
