### ISSUE TITLE
App device CORS Error 

### ISSUE THREAD

**Issue by guntercn** [JamesUgbanu/react-native-woocommerce-api#26]
HI.
I have an error when using the plugin since a device!

my error is when i use!

this.WooCommerce.get('products',data).then(result => {
         console.log(result);
      })
      .catch(error => {
             console.log(error);
      });

Config:

   this.WordPress =  new WooCommerceAPI({
      url: Config.WORDPRESS_URLS, // Your store URL
      ssl: true,
      wpAPIPrefix : 'MYPREFIX', 
      consumerKey:  'MYKEY' // Your consumer secret
      consumerSecret: 'MYCS', // Your consumer secret
      wpAPI: true, // Enable the WP REST API integration
      version: 'wc/v3', // WooCommerce WP REST API version
      queryStringAuth: true,
    }); 

if i running my project from a web, it works fine!
but when I compile the application and install it on an android device.
GET method never executes, only OPTIONS!

Thanks!

**Comment by JamesUgbanu** [comment]
Hi @guntercn CORS issue means the server is rejecting the request from that domain or app. You can go to the .htacess file on your website root directory to accept every request from that domain by simply adding additional headers. You can find a solution here - https://dev.to/robmarshall/wordpress-rest-api-cors-issues-13p7

Do let me if the solution above works for you so I will make this issue as resolved.

Thanks

**Comment by guntercn** [comment]
Hi James, 
thanks for you help, but there is still a problem with the plugin!

My server already has the settings for CORS.

Previously I was using @ woocommerce / woocommerce-rest-api. this plugin does not work with ionic 5 and angular 12

if i running my app on web "testing" the plugin "react-native-woocommerce-api" works fine, but the error is running on a device.

I had to implement new a class to handle the invocations to my woocommerce core 

//in the url concatenate the data keys for woocommerce
 let url = "products?consumer_key="+ Config.OAUTH_KEY +'&consumer_secret=' + Config.OAUTH_SECRET+'&page=1&featured=1'

//implement a wooheader function
return this.getCallHttp(Config.WORDPRESS_REST_WOO+url,data,this.wooHeader())

//I use native http
import { HTTP } from '@ionic-native/http/ngx';
//I use native http
public httpNative: HTTP

//and at the end I make the call by executing a get!
this.httpNative.get(url,parameters,header).then(res => {                                      
                  resolve(JSON.parse(res.data));
              }).catch(err => { .........

and 

thanks for the help, and good luck

**Comment by JamesUgbanu** [comment]
Hi Gutercn,

Thanks for your solution. However, I haven't tested this library on ionic yet. You can open a PR for this or I will look at supporting ionic in a future update.
