### ISSUE TITLE
Login API

### ISSUE THREAD

**Issue by sohaibjaved44** [JamesUgbanu/react-native-woocommerce-api#27]
First of all thanks for this very useful tool. Can you please share how we can login / authenticate a user with the help of this NPM?

**Comment by JamesUgbanu** [comment]
Hi @sohaibjaved44 

Thanks for finding this library helpful. If I get you clearly, do you want to login/authenticate with WordPress API through this library? If yes, there's a WordPress plugin that provides an API specifically for authenticating. See plugin   https://wordpress.org/plugins/jwt-auth/
