### ISSUE TITLE
Invalid signature - provided signature does not match

### ISSUE THREAD

**Issue by MAJIDNISAR** [JamesUgbanu/react-native-woocommerce-api#29]
there isnt any way to pass signature, i use the exact same ky cs and ck 
Object {
  "code": "woocommerce_rest_authentication_error",
  "data": Object {
    "status": 401,
  },
  "message": "Invalid signature - provided signature does not match.",
}

**Comment by JamesUgbanu** [comment]
Ensure your URL is correct, (http, or https).

**Comment by MAJIDNISAR** [comment]
the url is correct

**Comment by JamesUgbanu** [comment]
Are you making the request on HTTP or HTTPS and can I see the WC parameters used, excluding the key and secret?
