### ISSUE TITLE
woocommerce_rest_authentication_error

### ISSUE THREAD

**Issue by hellocaio** [JamesUgbanu/react-native-woocommerce-api#5]
Hi, I've been getting the error thrown at:

    if ( ! hash_equals( $signature, $consumer_signature ) ) { // @codingStandardsIgnoreLine
        return new WP_Error( '4woocommerce_rest_authentication_error', __( 'Invalid signature - provided signature does not match.', 'woocommerce' ), array( 'status' => 401 ) );
    }
**file: woocommerce/includes/api/class-wc-rest-authentication.php**

My setup is what the documentation shows:

    const Woocommerce = new WoocommerceAPI({
        url: AppConfig.siteURL, // Your store URL
        ssl: false,
        consumerKey: ck, // Your consumer secret
        consumerSecret: cs, // Your consumer secret
        wpAPI: true, // Enable the WP REST API integration
        version: "wc/v3", // WooCommerce WP REST API version
        queryStringAuth: true
    });

ck and cs are valid. I run it using Postman and I get a good response.

Here is my request, looks fine, expect that it is using v2 even though I specified v3.

    http://192.168.15.40/myproject/wp-json/wc/v2/products?oauth_consumer_key=###&oauth_nonce=###&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1560772341&oauth_version=1.0&oauth_signature=###=&

Request from Postman:

    http://localhost/myproject/wp-json/wc/v3/products?oauth_consumer_key=###&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1560770416&oauth_nonce=###&oauth_version=1.0&oauth_signature=###&page=2

They look very similar, except... you know what, it's the URL I think. I just ran Postman hard coding my local IP address and I get the same error. When I try with `localhost` instead of my IP address in react native I get a response of `undefined`. React native fetch does't like `localhost` form some reason.

Still not sure what to do. I'll post this here, someone else might have a similar problem.

**Comment by hellocaio** [comment]
I fixed this by going into Wordpress Configuration and changed my website address to `http://192.168.15.40/myproject/` and now my requests are accepted. 

If anyone knows a better solution, let me know. ;)

**Comment by JamesUgbanu** [comment]
You didn't point your IP properly, that was why you had the issue. Good you got it fixed.

**Comment by kishanbharda** [comment]
> http://192.168.15.40/myproject/

I have also same issue, even my url is simple like : http://slmp-550-4.slc.westdc.net/~web/bell/

Can anyone help me to solve this ?

**Comment by JamesUgbanu** [comment]
Before I can assist you further, can you share where you tested the endpoint? Either on postman or any other app. The error message shows there's a discrepancy in your setup and your WordPress website is rejecting the request.

**Comment by kishanbharda** [comment]
I tested on postman and it's worked. But, when I call api from react-native app, it's not working

**Comment by JamesUgbanu** [comment]
I can't help you if I can see your code. I need to see postman screenshot and your react native app code.

**Comment by kishanbharda** [comment]
Ok, so this is the url that I am calling to get products list :
http://slmp-550-4.slc.westdc.net/~web/bell/wp-json/wc/v3/products

Here is the postman response  : 
![image](https://user-images.githubusercontent.com/39869106/94514934-10537700-0240-11eb-8180-fcfef207bacf.png)

So, it is clear that my consumer_key and consumer_secret is right.

Now, I am calling same api using same consumer_key and consumer_secret using `react-native-woocommerce`, but I am getting this response : 
![image](https://user-images.githubusercontent.com/39869106/94515038-53ade580-0240-11eb-9e35-fad71a64f9b1.png)

Here is my code : 
```js
import React, { useEffect } from 'react';
import { Text, View } from 'react-native';
import WooCommerceAPI from 'react-native-woocommerce-api';

const Home = () => {
  useEffect(() => {
    const wcServer = new WooCommerceAPI({
      url: 'http://slmp-550-4.slc.westdc.net/~web/bell', // Your store URL
      ssl: false,
      consumerKey: 'my_consumer_key_same_as_postman', // Your consumer secret
      consumerSecret: 'my_consumer_secret_same_as_postman', // Your consumer secret
      wpAPI: true, // Enable the WP REST API integration
      version: 'wc/v3', // WooCommerce WP REST API version
      queryStringAuth: true,
    });

    wcServer
      .get('products')
      .then((data) => {
        console.log(data);
      })
      .catch((error) => {
        console.log(error);
      });
  });

  return (
    <View>
      <Text>Home</Text>
    </View>
  );
};

export default Home;
```

**Comment by JamesUgbanu** [comment]
We are edging closer to a solution. Let me see your Wordpress address as seen in the image attached.

**Comment by kishanbharda** [comment]
Here it is : 
WordPress Address(URL) : http://slmp-550-4.slc.westdc.net/~web/bell
Site Address (URL) : http://slmp-550-4.slc.westdc.net/~web/bell

![image](https://user-images.githubusercontent.com/39869106/94524724-9bd50400-0250-11eb-8d32-2adcd8ad866f.png)

**Comment by JamesUgbanu** [comment]
Can I have a look at you Authorization type on postman. See screenshot.

![auth type](https://user-images.githubusercontent.com/25230287/94531108-f875f600-0233-11eb-9348-6c2f2234300e.PNG)

**Comment by kishanbharda** [comment]
Postman Authorization type is OAuth 1.0 as you can see here :
![image](https://user-images.githubusercontent.com/39869106/94532919-1a836e80-025c-11eb-82e8-9635b15fd0f6.png)

**Comment by JamesUgbanu** [comment]
Change from http to https

   const wcServer = new WooCommerceAPI({
      url: 'https://slmp-550-4.slc.westdc.net/~web/bell', // Your store URL
      ssl: true,
      consumerKey: 'my_consumer_key_same_as_postman', // Your consumer secret
      consumerSecret: 'my_consumer_secret_same_as_postman', // Your consumer secret
      wpAPI: true, // Enable the WP REST API integration
      version: 'wc/v3', // WooCommerce WP REST API version
      queryStringAuth: true,
    });

![https](https://user-images.githubusercontent.com/25230287/94534169-f9a92200-0237-11eb-9de2-a255c191719a.PNG)

**Comment by kishanbharda** [comment]
Wow, it's worked. Thank you sooo much. Thank you for your time and appreciate your work man.

**Comment by JamesUgbanu** [comment]
Great! It worked. Do not forget to rate or star this library if it solved your problem. Thanks

**Comment by kishanbharda** [comment]
Yes, I already done it. Really, this is great library. I have tried woocommerce rest api but there is too much to set auth and other stuff. This library made it simple.

**Comment by cave21labs** [comment]
So this only works with SSL?

**Comment by Haseeb-ReactNative** [comment]
@JamesUgbanu  i have also have same issue. want to integrate woocommerce rest api with react native
<img width="520" alt="Screen Shot 2022-04-27 at 4 39 01 PM" src="https://user-images.githubusercontent.com/93119051/165510240-b3e5a908-5c80-4330-bc73-dc49923abab5.png">

**Comment by Haseeb-ReactNative** [comment]
<img width="458" alt="Screen Shot 2022-04-27 at 4 42 35 PM" src="https://user-images.githubusercontent.com/93119051/165510788-08d493d7-26ab-4f0a-b597-ae4891a7dd86.png">

**Comment by tahadiff** [comment]
Hello everyone,
@Haseeb-ReactNative @JamesUgbanu 
I am a newbie in react for call woocommerce rest API from react js. And facing the same issue as above, will the above package 'react-native-woocommerce-api' be workable for react js? or will you please guide me for another solution?
