### ISSUE TITLE
Error catching issue

### ISSUE THREAD

**Issue by emtoader** [JamesUgbanu/react-native-woocommerce-api#7]
Hi there!

When WooCommerce API return an error such as "Invalid email", the react native module doesn't catch the error and just returns an OK, but undefined object.

Therefore I cannot show the error in my interface, because I don't recieve any content.

**Comment by JamesUgbanu** [comment]
@emtoader Can you checkout and clone the Pull request I raised for this issue?
 link - https://github.com/JamesUgbanu/react-native-woocommerce-api/pull/8

**Please do let me know if you successfully clone the branch and if it worked for you. Thanks**

**### How to use**
// GET example
```
WooCommerceAPI.get('customers', function(err, data, res) {
  console.log(res);
});
```

// POST example
```
WooCommerceAPI.post('products', {
 product: {
   title: 'Premium Quality',
   type: 'simple',
    regular_price: '21.99'
  }
 }, function(err, data) {
  console.log(res);
 });
```

// Delete example
```
 WooCommerceAPI.delete('coupons/123', function(err, data) {
 console.log(res);
});
```

**Comment by JamesUgbanu** [comment]
Your feedback would be so appreciated as we run thorough test. Thanks

**Comment by emtoader** [comment]
Hi James,

I'm using Expo w/ RN and the new Pull Request needed the following dependecies:
var OAuth = require('oauth-1.0a');
var CryptoJS = require('crypto-js');
var Needle = require('needle');

After installing these packages I get the following error:
Unable to resovle module 'fs' from the 'needle' package.

I'm not a pro.
Let me know if you think I'm doing something wrong.

Here is my package.json:
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/masked-view": "0.1.5",
    "@react-navigation/drawer": "^5.3.2",
    "@react-navigation/material-bottom-tabs": "^5.1.6",
    "@react-navigation/native": "^5.1.1",
    "@react-navigation/stack": "^5.2.3",
    "crypto-js": "^4.0.0",
    "expo": "~36.0.0",
    "install": "^0.13.0",
    "needle": "^2.4.1",
    "npm": "^6.14.3",
    "oauth-1.0a": "^2.2.6",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-base64": "0.0.2",
    "react-native-card-list": "^0.1.0",
    "react-native-elements": "^1.2.7",
    "react-native-extra-dimensions-android": "^1.2.5",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-htmlview": "^0.15.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-loading-spinner-overlay": "^1.1.0",
    "react-native-modal": "^11.5.6",
    "react-native-numeric-input": "^1.8.3",
    "react-native-paper": "^3.6.0",
    "react-native-phone-call": "^1.0.9",
    "react-native-reanimated": "~1.4.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "~0.11.7",
    "react-native-webview": "^9.2.2",
    "react-native-woocommerce-api": "https://github.com/JamesUgbanu/react-native-woocommerce-api.git#bg-not-returning-error",
    "react-navigation": "^4.3.2",
    "react-navigation-drawer": "^2.4.6",
    "react-navigation-stack": "^2.3.4",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5"
  },
  "devDependencies": {
    "babel-preset-expo": "~8.0.0",
    "@babel/core": "^7.0.0"
  },
  "private": true
}

**Comment by emtoader** [comment]
The package at "node_modules\needle\lib\needle.js" attempted to import the Node standard library module "fs". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq/#can-i-use-nodejs-packages-with-expo

**Comment by emtoader** [comment]
Should I use something like https://github.com/philikon/ReactNativify ?

**Comment by JamesUgbanu** [comment]
Thanks for your feedback :(
I have removed needle completely because of its complexity. I now use node-fetch instead.

**Please fetch the current changes and try it like the code below;**


```
WooCommerceAPI.get('products')
          .then(data => {
          	console.log(data);
          })
          .catch(error => {
          	console.log(error);
          });
```

```
WooCommerceAPI.post('products', {})
          .then(data => {
          	console.log(data);
          })
          .catch(error => {
          	console.log(error);
          });
```

**Comment by JamesUgbanu** [comment]
@emtoader where you able to test it?
